# このファイルを使用するには./backend/Dockerfileの修正が必要！！（依存関係の部分）

services:
  yomitai_local_db:
    container_name: my_yomitai_local_db
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./backend/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    # expose:
    #   - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DB: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_CHARACTER_SET_SERVER: 'utf8mb4'
      MYSQL_COLLATION_SERVER: 'utf8mb4_unicode_ci'

  yomitai_backend:
    container_name: my_yomitai_backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend:/workspace
    ports:
      - "8000:8000"  # バックエンドのポート設定
    tty: true
    command: >
      /bin/sh -c '
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      '
    depends_on:
      - yomitai_local_db


  yomitai_frontend:
    container_name: my_yomitai_frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend:/code
    ports:
      - ${WEB_IP:-127.0.0.1}:5173:5173  # フロントエンドのポート設定
    tty: true
    command: >
      /bin/bash -c '
      cd app/ &&
      npm ci --cache /tmp/empty-cache &&
      npm run dev
      '

volumes:
  mysql-data: